[profile.default]
verbosity = 3
fs_permissions = [{ access = "read", path = "./" }]

[fmt]
bracket_spacing = true

## set only when the `hardhat` profile is selected
[profile.hardhat]
src = "contracts"
out = "artifacts"
libs = ["node_modules"]
fs_permissions = [{ access = "read", path = "./" }]
